// Node.js implementation of the Service Worker cache name build automation.
// Note: build.ps1 is a native PowerShell equivalent for environments without Node.js.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const projectRoot = path.join(__dirname, '..');

// Directories that aren't part of the shipped game (build output, tooling, docs, deps).
const excludedDirs = new Set([
  'node_modules', 'android', 'www', '.git', '.netlify', 'tests',
  'agents-library', 'tools', 'marketing', '.claude', '.vscode',
]);

// Loose root-level files that exist for dev/build tooling, not the shipped game,
// so editing them shouldn't force every client to redownload the app shell.
const excludedFiles = new Set([
  'build.js', 'capacitor.config.json', 'eslint.config.js',
  'package.json', 'package-lock.json', 'sw.js',
  'test.js', 'test2.js', 'test3.js',
  '__static-server.js', '__verify_marketing.js', '__verify_marketing2.js',
  // Generated by tools/bundle.js — the hash already reflects changes via its
  // ES module sources (app.js, ui-events.js, ui/tabs/*.js), so hashing the
  // generated bundle itself would just be redundant.
  'app.bundle.js', 'app.bundle.js.map',
  // Generated by tools/build-css.js from scss/main.scss — same reasoning.
  'style.css', 'style.css.map',
]);

const includedExtensions = new Set(['.js', '.css', '.scss', '.html']);

// Recursively collects every source file that actually ships with the game, so
// new files (e.g. under ui/tabs/) automatically participate in cache-busting
// instead of relying on a hand-maintained list that silently goes stale.
function collectSourceFiles(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') && entry.name !== '.') continue;
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (excludedDirs.has(entry.name)) continue;
      results.push(...collectSourceFiles(fullPath));
    } else {
      if (excludedFiles.has(entry.name)) continue;
      const ext = path.extname(entry.name);
      if (includedExtensions.has(ext) || entry.name === 'manifest.json') {
        results.push(fullPath);
      }
    }
  }
  return results;
}

try {
  console.log('Starting Service Worker Cache Name build automation...');

  const sourceFiles = collectSourceFiles(projectRoot).sort();
  console.log(`Hashing ${sourceFiles.length} source files...`);

  const hash = crypto.createHash('md5');
  for (const filePath of sourceFiles) {
    hash.update(fs.readFileSync(filePath));
  }

  const md5Hash = hash.digest('hex').substring(0, 10);
  const cacheName = `bank-empire-${md5Hash}`;
  console.log(`Generated MD5 Hash: ${md5Hash}`);
  console.log(`New Cache Name: ${cacheName}`);

  // Read and update sw.js
  const swPath = path.join(projectRoot, 'sw.js');
  if (!fs.existsSync(swPath)) {
    throw new Error('sw.js not found in workspace root.');
  }

  let swContent = fs.readFileSync(swPath, 'utf8');

  // Replace const CACHE_NAME = '...';
  const updatedSwContent = swContent.replace(
    /const\s+CACHE_NAME\s*=\s*['"`][^'"`]+['"`];/,
    `const CACHE_NAME = '${cacheName}';`
  );

  fs.writeFileSync(swPath, updatedSwContent, 'utf8');
  console.log('Successfully updated sw.js with the new CACHE_NAME!');
} catch (error) {
  console.error('Build failed:', error);
  process.exit(1);
}
